//  Based on https://github.com/nedseb/codal-stm32-iot-node/blob/master/model/STM32IotNodeIO.cpp
/*
  The MIT License (MIT)

  Copyright (c) 2017 Lancaster University.

  Permission is hereby granted, free of charge, to any person obtaining a
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation
  the rights to use, copy, modify, merge, publish, distribute, sublicense,
  and/or sell copies of the Software, and to permit persons to whom the
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.
*/

/**
  * Class definition for MicroBit NEXT IO.
  * Represents a collection of all I/O pins on the device.
  */

#include "CodalConfig.h"
#include "STM32BluePillIO.h"

using namespace codal;

/**
  * Constructor.
  *
  * Create a representation of all given I/O pins on the edge connector
  *
  * Accepts a sequence of unique ID's used to distinguish events raised
  * by MicroBitPin instances on the default EventModel.
  */
STM32BluePillIO::STM32BluePillIO() :
    // From https://docs.google.com/spreadsheets/d/1yLciHFyPfhRfwEcG3wfqHDgRFa5OoQYTk63bUmTboa8/edit#gid=0

    //  Pin Constructors are autogenerated. Do not update here
    pa0         (ID_PIN_PA0        , PA_0    , PIN_CAPABILITY_AD),
    pa1         (ID_PIN_PA1        , PA_1    , PIN_CAPABILITY_AD),
    pa2         (ID_PIN_PA2        , PA_2    , PIN_CAPABILITY_AD),
    pa3         (ID_PIN_PA3        , PA_3    , PIN_CAPABILITY_AD),
    pa4         (ID_PIN_PA4        , PA_4    , PIN_CAPABILITY_AD),
    pa5         (ID_PIN_PA5        , PA_5    , PIN_CAPABILITY_AD),
    pa6         (ID_PIN_PA6        , PA_6    , PIN_CAPABILITY_AD),
    pa7         (ID_PIN_PA7        , PA_7    , PIN_CAPABILITY_AD),
    pa8         (ID_PIN_PA8        , PA_8    , PIN_CAPABILITY_AD),
    pa9         (ID_PIN_PA9        , PA_9    , PIN_CAPABILITY_AD),
    pa10        (ID_PIN_PA10       , PA_10   , PIN_CAPABILITY_AD),
    pa11        (ID_PIN_PA11       , PA_11   , PIN_CAPABILITY_AD),
    pa12        (ID_PIN_PA12       , PA_12   , PIN_CAPABILITY_AD),
    pa13        (ID_PIN_PA13       , PA_13   , PIN_CAPABILITY_AD),
    pa14        (ID_PIN_PA14       , PA_14   , PIN_CAPABILITY_AD),
    pa15        (ID_PIN_PA15       , PA_15   , PIN_CAPABILITY_AD),
    pb0         (ID_PIN_PB0        , PB_0    , PIN_CAPABILITY_AD),
    pb1         (ID_PIN_PB1        , PB_1    , PIN_CAPABILITY_AD),
    pb2         (ID_PIN_PB2        , PB_2    , PIN_CAPABILITY_AD),
    pb3         (ID_PIN_PB3        , PB_3    , PIN_CAPABILITY_AD),
    pb4         (ID_PIN_PB4        , PB_4    , PIN_CAPABILITY_AD),
    pb5         (ID_PIN_PB5        , PB_5    , PIN_CAPABILITY_AD),
    pb6         (ID_PIN_PB6        , PB_6    , PIN_CAPABILITY_AD),
    pb7         (ID_PIN_PB7        , PB_7    , PIN_CAPABILITY_AD),
    pb8         (ID_PIN_PB8        , PB_8    , PIN_CAPABILITY_AD),
    pb9         (ID_PIN_PB9        , PB_9    , PIN_CAPABILITY_AD),
    pb10        (ID_PIN_PB10       , PB_10   , PIN_CAPABILITY_AD),
    pb11        (ID_PIN_PB11       , PB_11   , PIN_CAPABILITY_AD),
    pb12        (ID_PIN_PB12       , PB_12   , PIN_CAPABILITY_AD),
    pb13        (ID_PIN_PB13       , PB_13   , PIN_CAPABILITY_AD),
    pb14        (ID_PIN_PB14       , PB_14   , PIN_CAPABILITY_AD),
    pb15        (ID_PIN_PB15       , PB_15   , PIN_CAPABILITY_AD),
    //pc0         (ID_PIN_PC0        , PC_0    , PIN_CAPABILITY_AD),
    //pc1         (ID_PIN_PC1        , PC_1    , PIN_CAPABILITY_AD),
    //pc2         (ID_PIN_PC2        , PC_2    , PIN_CAPABILITY_AD),
    //pc3         (ID_PIN_PC3        , PC_3    , PIN_CAPABILITY_AD),
    //pc4         (ID_PIN_PC4        , PC_4    , PIN_CAPABILITY_AD),
    //pc5         (ID_PIN_PC5        , PC_5    , PIN_CAPABILITY_AD),
    //pc6         (ID_PIN_PC6        , PC_6    , PIN_CAPABILITY_AD),
    //pc7         (ID_PIN_PC7        , PC_7    , PIN_CAPABILITY_AD),
    //pc8         (ID_PIN_PC8        , PC_8    , PIN_CAPABILITY_AD),
    //pc9         (ID_PIN_PC9        , PC_9    , PIN_CAPABILITY_AD),
    //pc10        (ID_PIN_PC10       , PC_10   , PIN_CAPABILITY_AD),
    //pc11        (ID_PIN_PC11       , PC_11   , PIN_CAPABILITY_AD),
    //pc12        (ID_PIN_PC12       , PC_12   , PIN_CAPABILITY_AD),
    pc13        (ID_PIN_PC13       , PC_13   , PIN_CAPABILITY_AD),
    pc14        (ID_PIN_PC14       , PC_14   , PIN_CAPABILITY_AD),
    pc15        (ID_PIN_PC15       , PC_15   , PIN_CAPABILITY_AD),
    //pd2         (ID_PIN_PD2        , PD_2    , PIN_CAPABILITY_AD),
    //ph0         (ID_PIN_PH0        , PH_0    , PIN_CAPABILITY_AD),
    //ph1         (ID_PIN_PH1        , PH_1    , PIN_CAPABILITY_AD),
    adc0        (ID_PIN_ADC0       , PA_0    , PIN_CAPABILITY_ANALOG),
    adc1        (ID_PIN_ADC1       , PA_1    , PIN_CAPABILITY_ANALOG),
    adc2        (ID_PIN_ADC2       , PA_2    , PIN_CAPABILITY_ANALOG),
    adc3        (ID_PIN_ADC3       , PA_3    , PIN_CAPABILITY_ANALOG),
    adc4        (ID_PIN_ADC4       , PA_4    , PIN_CAPABILITY_ANALOG),
    adc5        (ID_PIN_ADC5       , PA_5    , PIN_CAPABILITY_ANALOG),
    adc6        (ID_PIN_ADC6       , PA_6    , PIN_CAPABILITY_ANALOG),
    adc7        (ID_PIN_ADC7       , PA_7    , PIN_CAPABILITY_ANALOG),
    adc8        (ID_PIN_ADC8       , PB_0    , PIN_CAPABILITY_ANALOG),
    adc9        (ID_PIN_ADC9       , PB_1    , PIN_CAPABILITY_ANALOG),
    adctemp     (ID_PIN_ADCTEMP    , ADC_TEMP, PIN_CAPABILITY_ANALOG),
    adcvref     (ID_PIN_ADCVREF    , ADC_VREF, PIN_CAPABILITY_ANALOG),
    adcvbat     (ID_PIN_ADCVBAT    , ADC_VBAT, PIN_CAPABILITY_ANALOG),
    temperature (ID_PIN_TEMPERATURE, ADC_TEMP, PIN_CAPABILITY_ANALOG),
    vref        (ID_PIN_VREF       , ADC_VREF, PIN_CAPABILITY_ANALOG),
    vbat        (ID_PIN_VBAT       , ADC_VBAT, PIN_CAPABILITY_ANALOG),
    led         (ID_PIN_LED        , PC_13   , PIN_CAPABILITY_DIGITAL),
    scl         (ID_PIN_SCL        , PB_6    , PIN_CAPABILITY_DIGITAL),
    sda         (ID_PIN_SDA        , PB_7    , PIN_CAPABILITY_DIGITAL),
    scl1        (ID_PIN_SCL1       , PB_6    , PIN_CAPABILITY_DIGITAL),
    sda1        (ID_PIN_SDA1       , PB_7    , PIN_CAPABILITY_DIGITAL),
    scl2        (ID_PIN_SCL2       , PB_10   , PIN_CAPABILITY_DIGITAL),
    sda2        (ID_PIN_SDA2       , PB_11   , PIN_CAPABILITY_DIGITAL),
    nss         (ID_PIN_NSS        , PA_4    , PIN_CAPABILITY_DIGITAL),
    sck         (ID_PIN_SCK        , PA_5    , PIN_CAPABILITY_DIGITAL),
    miso        (ID_PIN_MISO       , PA_6    , PIN_CAPABILITY_DIGITAL),
    mosi        (ID_PIN_MOSI       , PA_7    , PIN_CAPABILITY_DIGITAL),
    nss1        (ID_PIN_NSS1       , PA_4    , PIN_CAPABILITY_DIGITAL),
    sck1        (ID_PIN_SCK1       , PA_5    , PIN_CAPABILITY_DIGITAL),
    miso1       (ID_PIN_MISO1      , PA_6    , PIN_CAPABILITY_DIGITAL),
    mosi1       (ID_PIN_MOSI1      , PA_7    , PIN_CAPABILITY_DIGITAL),
    nss2        (ID_PIN_NSS2       , PB_12   , PIN_CAPABILITY_DIGITAL),
    sck2        (ID_PIN_SCK2       , PB_13   , PIN_CAPABILITY_DIGITAL),
    miso2       (ID_PIN_MISO2      , PB_14   , PIN_CAPABILITY_DIGITAL),
    mosi2       (ID_PIN_MOSI2      , PB_15   , PIN_CAPABILITY_DIGITAL),
    tx          (ID_PIN_TX         , PA_2    , PIN_CAPABILITY_DIGITAL),
    rx          (ID_PIN_RX         , PA_3    , PIN_CAPABILITY_DIGITAL),
    tx1         (ID_PIN_TX1        , PA_9    , PIN_CAPABILITY_DIGITAL),
    rx1         (ID_PIN_RX1        , PA_10   , PIN_CAPABILITY_DIGITAL),
    tx2         (ID_PIN_TX2        , PA_2    , PIN_CAPABILITY_DIGITAL),
    rx2         (ID_PIN_RX2        , PA_3    , PIN_CAPABILITY_DIGITAL),
    tx3         (ID_PIN_TX3        , PB_10   , PIN_CAPABILITY_DIGITAL),
    rx3         (ID_PIN_RX3        , PB_11   , PIN_CAPABILITY_DIGITAL),
    jtms        (ID_PIN_JTMS       , PA_13   , PIN_CAPABILITY_DIGITAL),
    jtck        (ID_PIN_JTCK       , PA_14   , PIN_CAPABILITY_DIGITAL),
    jtdi        (ID_PIN_JTDI       , PA_15   , PIN_CAPABILITY_DIGITAL),
    jtdo        (ID_PIN_JTDO       , PB_3    , PIN_CAPABILITY_DIGITAL),
    jtrst       (ID_PIN_JTRST      , PB_4    , PIN_CAPABILITY_DIGITAL),
    swdio       (ID_PIN_SWDIO      , PA_13   , PIN_CAPABILITY_DIGITAL),
    swclk       (ID_PIN_SWCLK      , PA_14   , PIN_CAPABILITY_DIGITAL),
    boot0       (ID_PIN_BOOT0      , BOOT0   , PIN_CAPABILITY_DIGITAL),
    boot1       (ID_PIN_BOOT1      , PB_2    , PIN_CAPABILITY_DIGITAL),
    wkup        (ID_PIN_WKUP       , PA_0    , PIN_CAPABILITY_DIGITAL),
    nrst        (ID_PIN_NRST       , NRST    , PIN_CAPABILITY_DIGITAL)

{
}
